# cloudbuild.frontend.yaml
steps:
  # Deploy statis ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "frontend-html"

options:
  logging: CLOUD_LOGGING_ONLY
