runtime: python39
entrypoint: ""

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)

  - url: /.*
    static_files: index.html
    upload: index.html
